FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY pipeline/ ./pipeline/
COPY data_generator/ ./data_generator/
COPY database/ ./database/
COPY config/ ./config/
COPY monitoring/ ./monitoring/

RUN mkdir -p logs models

ENV PYTHONUNBUFFERED=1

CMD ["python", "pipeline/producer.py"]
