apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: secom_pipeline
    user: ml_user
    secureJsonData:
      password: ml_password
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
    editable: true
